# Generated by Django 3.2.9 on 2021-12-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='d_o_b',
            new_name='birthday',
        ),
    ]
