# Generated by Django 4.0 on 2022-01-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_rename_d_o_b_userprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
