# Generated by Django 4.0 on 2022-01-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_userprofile_phone_number_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_check',
            field=models.BooleanField(default=False),
        ),
    ]
