# Generated by Django 4.0 on 2022-01-14 14:59

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0005_userprofile_two_factor_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, unique=True),
        ),
    ]
