# Generated by Django 4.0 on 2022-01-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0008_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
