# Generated by Django 4.0 on 2022-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0009_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
