# Generated by Django 4.0 on 2022-03-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='name',
            new_name='friends',
        ),
    ]
