# Generated by Django 4.0 on 2022-04-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('People', '0003_requests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='FriendRequest',
        ),
    ]
