# Generated by Django 4.0 on 2022-04-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('People', '0004_rename_requests_friendrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='FriendRequestList',
        ),
    ]
